package com.fairyteller.gles20boilerplate.material;

public class Illumination {

	private static final int ILLUM_COLOR_ON_AMBIENT_OFF = 0;
	private static final int ILLUM_COLOR_ON_AMBIENT_ON = 1;
	private static final int ILLUM_HIGHLIGHT_ON = 2;
	private static final int ILLUM_REFLECTION_ON_RAYTRACE_ON = 3;
	private static final int ILLUM_TRANSPARENCY_GLASS_ON_REFLECTION_RAYTRACE_ON = 4;
	private static final int ILLUM_REFLECTION_FRESNEL_ON_RAYTRACE_ON = 5;
	private static final int ILLUM_TRANSPARENCY_REFRACTION_ON_REFLECTION_FRESNEL_OFF_RAYTRACE_ON = 6;
	private static final int ILLUM_TRANSPARENCY_REFRACTION_ON_REFLECTION_FRESNEL_ON_RAYTRACE_ON = 7;
	private static final int ILLUM_REFLECTION_ON_RAYTRACE_OFF = 8;
	private static final int ILLUM_TRANSPARENCY_GLASS_ON_REFLECTION_RAYTRACE_OFF = 9;
	private static final int ILLUM_CASTS_SHADOW_ONTO_INVISIBLE_SURFACES = 10;

	public enum IlluminationModel {
		COLOR_ON_AMBIENT_OFF, 
		COLOR_ON_AMBIENT_ON, 
		HIGHLIGHT_ON, 
		REFLECTION_ON_RAYTRACE_ON, 
		TRANSPARENCY_GLASS_ON_REFLECTION_RAYTRACE_ON, 
		REFLECTION_FRESNEL_ON_RAYTRACE_ON, 
		TRANSPARENCY_REFRACTION_ON_REFLECTION_FRESNEL_OFF_RAYTRACE_ON, 
		TRANSPARENCY_REFRACTION_ON_REFLECTION_FRESNEL_ON_RAYTRACE_ON, 
		REFLECTION_ON_RAYTRACE_OFF, 
		TRANSPARENCY_GLASS_ON_REFLECTION_RAYTRACE_OFF, 
		CASTS_SHADOW_ONTO_INVISIBLE_SURFACES, 
		unspecified
	}

	public static IlluminationModel getIlluminationModel(int illum) {
		switch (illum) {
		case ILLUM_COLOR_ON_AMBIENT_OFF:
			return IlluminationModel.COLOR_ON_AMBIENT_OFF;
		case ILLUM_COLOR_ON_AMBIENT_ON:
			return IlluminationModel.COLOR_ON_AMBIENT_ON;
		case ILLUM_HIGHLIGHT_ON:
			return IlluminationModel.HIGHLIGHT_ON;
		case ILLUM_REFLECTION_ON_RAYTRACE_ON:
			return IlluminationModel.REFLECTION_ON_RAYTRACE_ON;
		case ILLUM_TRANSPARENCY_GLASS_ON_REFLECTION_RAYTRACE_ON:
			return IlluminationModel.TRANSPARENCY_GLASS_ON_REFLECTION_RAYTRACE_ON;
		case ILLUM_REFLECTION_FRESNEL_ON_RAYTRACE_ON:
			return IlluminationModel.REFLECTION_FRESNEL_ON_RAYTRACE_ON;
		case ILLUM_TRANSPARENCY_REFRACTION_ON_REFLECTION_FRESNEL_OFF_RAYTRACE_ON:
			return IlluminationModel.TRANSPARENCY_REFRACTION_ON_REFLECTION_FRESNEL_OFF_RAYTRACE_ON;
		case ILLUM_TRANSPARENCY_REFRACTION_ON_REFLECTION_FRESNEL_ON_RAYTRACE_ON:
			return IlluminationModel.TRANSPARENCY_REFRACTION_ON_REFLECTION_FRESNEL_ON_RAYTRACE_ON;
		case ILLUM_REFLECTION_ON_RAYTRACE_OFF:
			return IlluminationModel.REFLECTION_ON_RAYTRACE_OFF;
		case ILLUM_TRANSPARENCY_GLASS_ON_REFLECTION_RAYTRACE_OFF:
			return IlluminationModel.TRANSPARENCY_GLASS_ON_REFLECTION_RAYTRACE_OFF;
		case ILLUM_CASTS_SHADOW_ONTO_INVISIBLE_SURFACES:
			return IlluminationModel.CASTS_SHADOW_ONTO_INVISIBLE_SURFACES;
		default:
			return IlluminationModel.unspecified;
		}
	}
}
